MDM 7.2.1 war file deployed on Tomcat 8.5 : Error java.lang.NoSuchMethodError: javax.servlet.ServletContext.getSessionTimeout() (#834)
(cherry picked from commit bef0b1ef04ea41c280058fd37d1325187b35eb2d)